# Generated by Django 6.0.4 on 2026-04-23 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('starter_code', models.TextField(help_text='The buggy starter code shown to the Taker.')),
                ('solution_code', models.TextField(help_text='The intended solution to be revealed after 5 failures.')),
                ('difficulty', models.CharField(choices=[('EZ', 'Easy'), ('MD', 'Medium'), ('HD', 'Hard')], default='EZ', max_length=2)),
                ('language', models.CharField(default='python', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.TextField(help_text='The arguments or standard input provided to the code.')),
                ('expected_output', models.TextField(help_text='The exact expected stdout or return value.')),
                ('hidden_flag', models.BooleanField(default=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='api.challenge')),
            ],
        ),
    ]
